level:
  name: "Hard Boiled"
  shape: Hexagonal
  size: 7
  blocks:
    # first row
    - { q: 0, r: -3, block: Basic }
    - { q: 1, r: -3, block: Basic }
    - { q: 2, r: -3, block: Basic }
    - { q: 3, r: -3, block: Basic }
    # second row
    - { q: -1, r: -2, block: Basic }
    - { q: 0, r: -2, block: Basic2 }
    - { q: 1, r: -2, block: Basic2 }
    - { q: 2, r: -2, block: Basic2 }
    - { q: 3, r: -2, block: Basic }
    # third row
    - { q: -2, r: -1, block: Basic }
    - { q: -1, r: -1, block: Basic2 }
    - { q: 0, r: -1, block: Basic3 }
    - { q: 1, r: -1, block: Basic3 }
    - { q: 2, r: -1, block: Basic2 }
    - { q: 3, r: -1, block: Basic }
    # fourth row
    - { q: -3, r: 0, block: Basic }
    - { q: -2, r: 0, block: Basic2 }
    - { q: -1, r: 0, block: Basic3 }
    - { q: 0, r: 0, block: Basic3 }
    - { q: 1, r: 0, block: Basic3 }
    - { q: 2, r: 0, block: Basic2 }
    - { q: 3, r: 0, block: Basic }
    # fifth row
    - { q: -3, r: 1, block: Basic }
    - { q: -2, r: 1, block: Basic2 }
    - { q: -1, r: 1, block: Basic3 }
    - { q: 0, r: 1, block: Basic3 }
    - { q: 1, r: 1, block: Basic2 }
    - { q: 2, r: 1, block: Basic }
    # sixth row
    - { q: -3, r: 2, block: Basic }
    - { q: -2, r: 2, block: Basic2 }
    - { q: -1, r: 2, block: Basic2 }
    - { q: 0, r: 2, block: Basic2 }
    - { q: 1, r: 2, block: Basic }
    # seventh row
    - { q: -3, r: 3, block: Basic }
    - { q: -2, r: 3, block: Basic }
    - { q: -1, r: 3, block: Basic }
    - { q: 0, r: 3, block: Basic }
